In [149]:
import numpy as np
import pandas as pd
from collections import OrderedDict, Counter
import itertools
meital = pd.read_clipboard(parse_dates=['StartDate', 'StartTime'])


In [153]:
grouped = meital.drop(columns='Cage').groupby(['StartDate', 'StartTime'])
group_all_mices = grouped.mean().reset_index()
date_time = pd.to_datetime(group_all_mices['StartDate'].astype('string') + " " + group_all_mices['StartTime'].astype('string'))
group_all_mices = group_all_mices.drop(columns=['StartDate', 'StartTime'])
group_all_mices = group_all_mices.set_index(date_time)
# group_all_mices[group_all_mices.index.hour >= 8].head(110)


In [155]:
group_all_mices

In_g
2020-10-01 15:06:19-18:00  0.032
2020-10-01 15:17:20-18:00  0.129
2020-10-01 15:17:26-18:00  0.004
2020-10-01 15:18:38-18:00  0.009
2020-10-01 15:20:46-18:00  0.049
...                          ...
2020-10-18 08:00:35-18:00  0.112
2020-10-18 08:00:39-18:00  0.020
2020-10-18 08:02:39-18:00  0.091
2020-10-18 08:02:40-18:00  0.004
2020-10-18 08:04:11-18:00  0.004

[5109 rows x 1 columns]

In [156]:
set_hours = sorted(group_all_mices.index.hour.unique())

In [157]:
dates = sorted(set(group_all_mices.index.date))

In [158]:
hours_array = group_all_mices.index.hour
dates_array = group_all_mices.index.date
date_hour_sets = np.array(list(zip(dates_array, hours_array)))

In [159]:
index = group_all_mices.index

In [160]:
def replace_ids_to_group_id(pd_index):
    dates = sorted(set(pd_index.date))

    conditiones = [ logic 
        for date in dates 
        for logic in [
          (np.logical_and((pd_index.hour < 7), (pd_index.date == date))), 
          (np.logical_and((pd_index.hour >= 7), (pd_index.date == date)))] 
      ]
    choices = list(range(len(conditiones)))
    pd_index
    return np.select(conditiones, choices, pd_index.factorize()[0])
group_all_mices['days_exp'] = replace_ids_to_group_id(index)


In [161]:
group_all_mices.groupby('days_exp').sum()

In_g
days_exp         
1         34.7175
2         14.4750
3          7.7160
4          6.1600
5         50.1930
6         16.0400
7         12.2290
8          6.2040
9         55.9230
10        18.8030
11        11.6310
12         4.2130
13        58.4630
14        21.2450
15        13.9050
16         4.8820
17        63.9800
18        22.9120
19        10.0100
20         5.3960
21        66.3180
22        18.7485
23        71.1515
24        28.2490
25         9.8150
26         5.8000
27        74.4300
28        17.3960
29        10.5430
30        11.2570
31        71.7120
32        17.4005
33         6.2440
34         6.5050
35         8.8810

In [162]:
[ logic 
        for date in dates 
        for logic in [
          (np.logical_and((index.hour < 8), (index.date == date))), 
          (np.logical_and((index.hour >= 8), (index.date == date)))] 
]

[array([False, False, False, ..., False, False, False]),
 array([ True,  True,  True, ..., False, False, False]),
 array([False, False, False, ..., False, False, False]),
 array([False, False, False, ..., False, False, False]),
 array([False, False, False, ..., False, False, False]),
 array([False, False, False, ..., False, False, False]),
 array([False, False, False, ..., False, False, False]),
 array([False, False, False, ..., False, False, False]),
 array([False, False, False, ..., False, False, False]),
 array([False, False, False, ..., False, False, False]),
 array([False, False, False, ..., False, False, False]),
 array([False, False, False, ..., False, False, False]),
 array([False, False, False, ..., False, False, False]),
 array([False, False, False, ..., False, False, False]),
 array([False, False, False, ..., False, False, False]),
 array([False, False, False, ..., False, False, False]),
 array([False, False, False, ..., False, False, False]),
 array([False, False, False, ..

In [131]:
for date in dates:
  log = [np.logical_and((index.hour < 8), (index.date == date))]
  print(any(log[0]))

False
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True


In [130]:
dates

[datetime.date(2020, 10, 1),
 datetime.date(2020, 10, 2),
 datetime.date(2020, 10, 3),
 datetime.date(2020, 10, 4),
 datetime.date(2020, 10, 5),
 datetime.date(2020, 10, 6),
 datetime.date(2020, 10, 7),
 datetime.date(2020, 10, 8),
 datetime.date(2020, 10, 9),
 datetime.date(2020, 10, 10),
 datetime.date(2020, 10, 11),
 datetime.date(2020, 10, 12),
 datetime.date(2020, 10, 13),
 datetime.date(2020, 10, 14),
 datetime.date(2020, 10, 15),
 datetime.date(2020, 10, 16),
 datetime.date(2020, 10, 17),
 datetime.date(2020, 10, 18)]